#!/bin/sh
export NNN_PLUG='f:~/.config/nnn/plugins/fzopen;d:~/.config/nnn/plugins/fzcd;p:~/.config/nnn/plugins/preview-tui;'

# Customize colors. 00 means default. Other colors are hexa versionf of the xterm colors i.e 231 (ffffff) is E6 in hexa.
BLK="00" CHR="00" DIR="E6" EXE="31" REG="00" HARDLINK="00" SYMLINK="06" MISSING="00" ORPHAN="00" FIFO="00" SOCK="00" OTHER="00"
export NNN_FCOLORS="$BLK$CHR$DIR$EXE$REG$HARDLINK$SYMLINK$MISSING$ORPHAN$FIFO$SOCK$OTHER"

# Using bat style full instead of number
export NNN_BATSTYLE="full"

#Open nnn with hidden files shown and preview plugin enabled
alias nnn='nnn -H -Pp -a'

# Set cd on quit if using ^G
n ()
{
    # Block nesting of nnn in subshells
    [ "${NNNLVL:-0}" -eq 0 ] || {
        echo "nnn is already running"
        return
    }

    # The behaviour is set to cd on quit (nnn checks if NNN_TMPFILE is set)
    # If NNN_TMPFILE is set to a custom path, it must be exported for nnn to
    # see. To cd on quit only on ^G, remove the "export" and make sure not to
    # use a custom path, i.e. set NNN_TMPFILE *exactly* as follows:
    NNN_TMPFILE="${XDG_CONFIG_HOME:-$HOME/.config}/nnn/.lastd"
    # export NNN_TMPFILE="${XDG_CONFIG_HOME:-$HOME/.config}/nnn/.lastd"

    # Unmask ^Q (, ^V etc.) (if required, see `stty -a`) to Quit nnn
    # stty start undef
    # stty stop undef
    # stty lwrap undef
    # stty lnext undef

    # The command builtin allows one to alias nnn to n, if desired, without
    # making an infinitely recursive alias
    command nnn -H -Pp -a "$@"

    [ ! -f "$NNN_TMPFILE" ] || {
        . "$NNN_TMPFILE"
        rm -f -- "$NNN_TMPFILE" > /dev/null
    }
}
